// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @const
 * @namespace
 */
var lptc_coderdojo = lptc_coderdojo || {};

/**
 * @const
 * @namespace
 */
lptc_coderdojo.protocol = lptc_coderdojo.protocol || {};

/**
 * @enum
 */
lptc_coderdojo.protocol.MessageType = {
  Error: 0, 0: 'Error',
  DeviceData: 1, 1: 'DeviceData'
};

/**
 * @enum
 */
lptc_coderdojo.protocol.DataType = {
  Depth: 0, 0: 'Depth',
  Video: 1, 1: 'Video'
};

/**
 * @constructor
 */
lptc_coderdojo.protocol.DeviceData = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {lptc_coderdojo.protocol.DeviceData}
 */
lptc_coderdojo.protocol.DeviceData.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {lptc_coderdojo.protocol.DeviceData=} obj
 * @returns {lptc_coderdojo.protocol.DeviceData}
 */
lptc_coderdojo.protocol.DeviceData.getRootAsDeviceData = function(bb, obj) {
  return (obj || new lptc_coderdojo.protocol.DeviceData).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {lptc_coderdojo.protocol.DataType}
 */
lptc_coderdojo.protocol.DeviceData.prototype.type = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? /** @type {lptc_coderdojo.protocol.DataType} */ (this.bb.readUint8(this.bb_pos + offset)) : lptc_coderdojo.protocol.DataType.Depth;
};

/**
 * @param {number} index
 * @returns {number}
 */
lptc_coderdojo.protocol.DeviceData.prototype.depth = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns {number}
 */
lptc_coderdojo.protocol.DeviceData.prototype.depthLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Uint8Array}
 */
lptc_coderdojo.protocol.DeviceData.prototype.depthArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {number} index
 * @returns {number}
 */
lptc_coderdojo.protocol.DeviceData.prototype.video = function(index) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.readUint8(this.bb.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns {number}
 */
lptc_coderdojo.protocol.DeviceData.prototype.videoLength = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns {Uint8Array}
 */
lptc_coderdojo.protocol.DeviceData.prototype.videoArray = function() {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb.bytes().buffer, this.bb.bytes().byteOffset + this.bb.__vector(this.bb_pos + offset), this.bb.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
lptc_coderdojo.protocol.DeviceData.startDeviceData = function(builder) {
  builder.startObject(3);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {lptc_coderdojo.protocol.DataType} type
 */
lptc_coderdojo.protocol.DeviceData.addType = function(builder, type) {
  builder.addFieldInt8(0, type, lptc_coderdojo.protocol.DataType.Depth);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} depthOffset
 */
lptc_coderdojo.protocol.DeviceData.addDepth = function(builder, depthOffset) {
  builder.addFieldOffset(1, depthOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
lptc_coderdojo.protocol.DeviceData.createDepthVector = function(builder, data) {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
lptc_coderdojo.protocol.DeviceData.startDepthVector = function(builder, numElems) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} videoOffset
 */
lptc_coderdojo.protocol.DeviceData.addVideo = function(builder, videoOffset) {
  builder.addFieldOffset(2, videoOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {Array.<number>} data
 * @returns {flatbuffers.Offset}
 */
lptc_coderdojo.protocol.DeviceData.createVideoVector = function(builder, data) {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {number} numElems
 */
lptc_coderdojo.protocol.DeviceData.startVideoVector = function(builder, numElems) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
lptc_coderdojo.protocol.DeviceData.endDeviceData = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @constructor
 */
lptc_coderdojo.protocol.Message = function() {
  /**
   * @type {flatbuffers.ByteBuffer}
   */
  this.bb = null;

  /**
   * @type {number}
   */
  this.bb_pos = 0;
};

/**
 * @param {number} i
 * @param {flatbuffers.ByteBuffer} bb
 * @returns {lptc_coderdojo.protocol.Message}
 */
lptc_coderdojo.protocol.Message.prototype.__init = function(i, bb) {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param {flatbuffers.ByteBuffer} bb
 * @param {lptc_coderdojo.protocol.Message=} obj
 * @returns {lptc_coderdojo.protocol.Message}
 */
lptc_coderdojo.protocol.Message.getRootAsMessage = function(bb, obj) {
  return (obj || new lptc_coderdojo.protocol.Message).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns {flatbuffers.Long}
 */
lptc_coderdojo.protocol.Message.prototype.timestamp = function() {
  var offset = this.bb.__offset(this.bb_pos, 4);
  return offset ? this.bb.readUint64(this.bb_pos + offset) : this.bb.createLong(0, 0);
};

/**
 * @returns {lptc_coderdojo.protocol.MessageType}
 */
lptc_coderdojo.protocol.Message.prototype.type = function() {
  var offset = this.bb.__offset(this.bb_pos, 6);
  return offset ? /** @type {lptc_coderdojo.protocol.MessageType} */ (this.bb.readUint8(this.bb_pos + offset)) : lptc_coderdojo.protocol.MessageType.Error;
};

/**
 * @param {flatbuffers.Encoding=} optionalEncoding
 * @returns {string|Uint8Array|null}
 */
lptc_coderdojo.protocol.Message.prototype.error = function(optionalEncoding) {
  var offset = this.bb.__offset(this.bb_pos, 8);
  return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param {lptc_coderdojo.protocol.DeviceData=} obj
 * @returns {lptc_coderdojo.protocol.DeviceData|null}
 */
lptc_coderdojo.protocol.Message.prototype.data = function(obj) {
  var offset = this.bb.__offset(this.bb_pos, 10);
  return offset ? (obj || new lptc_coderdojo.protocol.DeviceData).__init(this.bb.__indirect(this.bb_pos + offset), this.bb) : null;
};

/**
 * @param {flatbuffers.Builder} builder
 */
lptc_coderdojo.protocol.Message.startMessage = function(builder) {
  builder.startObject(4);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Long} timestamp
 */
lptc_coderdojo.protocol.Message.addTimestamp = function(builder, timestamp) {
  builder.addFieldInt64(0, timestamp, builder.createLong(0, 0));
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {lptc_coderdojo.protocol.MessageType} type
 */
lptc_coderdojo.protocol.Message.addType = function(builder, type) {
  builder.addFieldInt8(1, type, lptc_coderdojo.protocol.MessageType.Error);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} errorOffset
 */
lptc_coderdojo.protocol.Message.addError = function(builder, errorOffset) {
  builder.addFieldOffset(2, errorOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} dataOffset
 */
lptc_coderdojo.protocol.Message.addData = function(builder, dataOffset) {
  builder.addFieldOffset(3, dataOffset, 0);
};

/**
 * @param {flatbuffers.Builder} builder
 * @returns {flatbuffers.Offset}
 */
lptc_coderdojo.protocol.Message.endMessage = function(builder) {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param {flatbuffers.Builder} builder
 * @param {flatbuffers.Offset} offset
 */
lptc_coderdojo.protocol.Message.finishMessageBuffer = function(builder, offset) {
  builder.finish(offset);
};

// Exports for Node.js and RequireJS
this.lptc_coderdojo = lptc_coderdojo;
